# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vjsD+Bp7+QIInXFAvATGW91055Fh+YQR6itLveSwyR1p++66mjlI7bKEZkHgsyJd94f0y3HuT/r9vvTeT+54q+aQ5FErkRAXz+CBQ2pdcleJG/Wupy9sMYjRDcUk3EcgC85fETVZDI35Sm+q+RJy+6QMLVrdbZ2P8Gd8glUyNkaEqHDGEePXy71thDm1j8jiMLHnEbXS/8r7x0HgGlUTe895wHirJiakE3G8ahY5NIImlfYtX6rsFlRL95cMzhk2VuYMKk+GNXoURKyKweF3CRW5k/5ipOakENErVVK2PQWifIYdWzd2jH1uPdESISraKXX2JyOX7TQzgUKrcI23Wh8Ff8TCdNz+gMiCwCDNPdJ63AQkHzkgl/FJ6RjrFp9HxvKdo8/lB031TAM2NFdhx7ab5duSR4W0BhaMdSWc7XnbNfIj801tB9A+epfa4MLTi6N783O+q9ILKaWeBjBc2XB1KAB7Na9HSOqucvMW/W40LjEXDW4MArmyCvvofP+JCqQ/xW9JKqlyNyyxA1QvW2cExxw3lkk8SKtZTAPqzpBtV2f0CA5sSa7D73wTBcLyt8PHoYdMH3Fk5aTWtPxKMdVlaic5tdSPY8k7A8LlmlUGsQZEeOitOW5BsljY9hs82PdcpaH2kKipvWOfW/ttn5WEmjJ05DTpN/h/GzVP47o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
