travis:
  secure:
    BINSTAR_TOKEN: aRVGr/bBhYJ16Rr+AgTi4Mzp76olSSP0/2LyjCzDJeyt2nu1IPop0PPSMEEyLnIiwfhAMZWk8lnDhC5zY5dKuw7qrQ44+IRDBjfoY4oQh0kKZH/pGqAUBoAsuSB0v9jmuIwqfK7uSzEXFWuq+EzFW3iytUYIwyFmFsYNOnjHP4Li98c8siMrnhUnQd8Mm+oOXBpQlZYQ4R7UWXO/Awe33NcyEt7V0PjYDxSVOv8rdf93vw0q++guAESWBDXmfR96d5sdp+K5uuK/NSHX0p6zUPu6PJ+9qZyFBybKtv8/2ugxMVocU+gFXFwI+L1xJGv2r3vRiMIh+zBdwf0lNZgbAuQzJxkPiagwZqZXwg7E4t/81al8PgvQyaOwvR5eFyQ/yZ8ZrHECr7jF3dwFexw/vd3Yab+0VKwHApZQ5nyK04ooo94dslKKBaUifmEC6Vh9dOEfuTiosahPDi9eTtzHurFm0/XY/o5uR31KoBf1sOIAAqzxZgEAqXknyvargqaWC7/QOnMWvcqWMpDggFpJmOCVC7YssnrcgFQthGObU3Tea7y/GugZkKKbXGM6iY2d/3xAWzJvM3xw7V1Sevgj7kBFVDE994IMkfovhLU5xeFdQ9xk4btU+RXr5UlgiAj4TMbtsMuTClew51VNzjOu/EIq+bU9Q8ZlVM9BcI+p3jw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
