travis:
  secure:
    BINSTAR_TOKEN: vjsD+Bp7+QIInXFAvATGW91055Fh+YQR6itLveSwyR1p++66mjlI7bKEZkHgsyJd94f0y3HuT/r9vvTeT+54q+aQ5FErkRAXz+CBQ2pdcleJG/Wupy9sMYjRDcUk3EcgC85fETVZDI35Sm+q+RJy+6QMLVrdbZ2P8Gd8glUyNkaEqHDGEePXy71thDm1j8jiMLHnEbXS/8r7x0HgGlUTe895wHirJiakE3G8ahY5NIImlfYtX6rsFlRL95cMzhk2VuYMKk+GNXoURKyKweF3CRW5k/5ipOakENErVVK2PQWifIYdWzd2jH1uPdESISraKXX2JyOX7TQzgUKrcI23Wh8Ff8TCdNz+gMiCwCDNPdJ63AQkHzkgl/FJ6RjrFp9HxvKdo8/lB031TAM2NFdhx7ab5duSR4W0BhaMdSWc7XnbNfIj801tB9A+epfa4MLTi6N783O+q9ILKaWeBjBc2XB1KAB7Na9HSOqucvMW/W40LjEXDW4MArmyCvvofP+JCqQ/xW9JKqlyNyyxA1QvW2cExxw3lkk8SKtZTAPqzpBtV2f0CA5sSa7D73wTBcLyt8PHoYdMH3Fk5aTWtPxKMdVlaic5tdSPY8k7A8LlmlUGsQZEeOitOW5BsljY9hs82PdcpaH2kKipvWOfW/ttn5WEmjJ05DTpN/h/GzVP47o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
